spring.application.name=movieflix
spring.datasource.url=jdbc:postgresql://localhost:5432/db_moviefilx
spring.datasource.username=admin
spring.datasource.password=123456
movieflix.secret.key=cwlF2Oaop55fKptbewmnsjHwaDh0LyNN
